package com.tadgreen.entity;
// Generated Apr 3, 2023, 10:50:00 AM by Hibernate Tools 4.3.6.Final

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CartId generated by hbm2java
 */
@Embeddable
public class CartId implements java.io.Serializable {

	private Serializable productId;
	private Serializable userId;

	public CartId() {
	}

	public CartId(Serializable productId, Serializable userId) {
		this.productId = productId;
		this.userId = userId;
	}

	@Column(name = "ProductID", nullable = false)
	public Serializable getProductId() {
		return this.productId;
	}

	public void setProductId(Serializable productId) {
		this.productId = productId;
	}

	@Column(name = "UserID", nullable = false)
	public Serializable getUserId() {
		return this.userId;
	}

	public void setUserId(Serializable userId) {
		this.userId = userId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CartId))
			return false;
		CartId castOther = (CartId) other;

		return ((this.getProductId() == castOther.getProductId()) || (this.getProductId() != null
				&& castOther.getProductId() != null && this.getProductId().equals(castOther.getProductId())))
				&& ((this.getUserId() == castOther.getUserId()) || (this.getUserId() != null
						&& castOther.getUserId() != null && this.getUserId().equals(castOther.getUserId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getProductId() == null ? 0 : this.getProductId().hashCode());
		result = 37 * result + (getUserId() == null ? 0 : this.getUserId().hashCode());
		return result;
	}

}
