package com.tadgreen.entity;
// Generated Apr 3, 2023, 10:50:00 AM by Hibernate Tools 4.3.6.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * District generated by hbm2java
 */
@Entity
@Table(name = "District", schema = "dbo", catalog = "DB_Tad")
public class District implements java.io.Serializable {

	private Serializable districtId;
	private Province province;
	private Serializable name;
	private Set<Ward> wards = new HashSet<Ward>(0);

	public District() {
	}

	public District(Serializable districtId, Province province, Serializable name) {
		this.districtId = districtId;
		this.province = province;
		this.name = name;
	}

	public District(Serializable districtId, Province province, Serializable name, Set<Ward> wards) {
		this.districtId = districtId;
		this.province = province;
		this.name = name;
		this.wards = wards;
	}

	@Id

	@Column(name = "DistrictID", unique = true, nullable = false)
	public Serializable getDistrictId() {
		return this.districtId;
	}

	public void setDistrictId(Serializable districtId) {
		this.districtId = districtId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ProvinceID", nullable = false)
	public Province getProvince() {
		return this.province;
	}

	public void setProvince(Province province) {
		this.province = province;
	}

	@Column(name = "Name", nullable = false)
	public Serializable getName() {
		return this.name;
	}

	public void setName(Serializable name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "district")
	public Set<Ward> getWards() {
		return this.wards;
	}

	public void setWards(Set<Ward> wards) {
		this.wards = wards;
	}

}
