package com.tadgreen.entity;
// Generated Apr 3, 2023, 10:50:00 AM by Hibernate Tools 4.3.6.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ward generated by hbm2java
 */
@Entity
@Table(name = "Ward", schema = "dbo", catalog = "DB_Tad")
public class Ward implements java.io.Serializable {

	private Serializable wardId;
	private District district;
	private Serializable name;
	private Set<Address> addresses = new HashSet<Address>(0);

	public Ward() {
	}

	public Ward(Serializable wardId, District district, Serializable name) {
		this.wardId = wardId;
		this.district = district;
		this.name = name;
	}

	public Ward(Serializable wardId, District district, Serializable name, Set<Address> addresses) {
		this.wardId = wardId;
		this.district = district;
		this.name = name;
		this.addresses = addresses;
	}

	@Id

	@Column(name = "WardID", unique = true, nullable = false)
	public Serializable getWardId() {
		return this.wardId;
	}

	public void setWardId(Serializable wardId) {
		this.wardId = wardId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DistrictID", nullable = false)
	public District getDistrict() {
		return this.district;
	}

	public void setDistrict(District district) {
		this.district = district;
	}

	@Column(name = "Name", nullable = false)
	public Serializable getName() {
		return this.name;
	}

	public void setName(Serializable name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ward")
	public Set<Address> getAddresses() {
		return this.addresses;
	}

	public void setAddresses(Set<Address> addresses) {
		this.addresses = addresses;
	}

}
