package tad.entity;
// Generated Apr 8, 2023, 3:38:47 PM by Hibernate Tools 3.6.2.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Account generated by hbm2java
 */
@Entity
@Table(name = "Account", schema = "dbo", catalog = "DB_Tad")
public class Account {

	@Id
	@GeneratedValue
	@Column(name = "AccountID", unique = true, nullable = false)
	private int accountId;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RoleID", nullable = false)
	private Role role;

	@Column(name = "LastName", nullable = false)
	private String lastName;

	@Column(name = "FirstName", nullable = false)
	private String firstName;

	@Column(name = "Email", nullable = false)
	private String email;

	@Column(name = "PhoneNumber")
	private String phoneNumber;

	@Column(name = "Avatar")
	private String avatar;
	@Column(name = "Status", nullable = false)
	private int state;

	@Column(name = "Password", nullable = false)
	private String password;

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "accounts")
	private Set<Address> addresses = new HashSet<Address>(0);

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "account")
	private Set<Order> orders = new HashSet<Order>(0);

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "account")
	private Set<Comment> comments = new HashSet<Comment>(0);

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "account")
	private Set<Feedback> feedbacks = new HashSet<Feedback>(0);

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "account")
	private Set<Cart> carts = new HashSet<Cart>(0);

	public Account() {
	}

	public Account(Role role, String lastName, String firstName, String email,  String avatar,String password) {
		this.role = role;
		this.lastName = lastName;
		this.firstName = firstName;
		this.email = email;
		this.avatar = avatar;
		this.state = 1; // Tao tk moi thi set tk do o trang thai mo
		this.password = password;
	}

	public Account(Role role, String lastName, String firstName,
			String email, String phoneNumber, String avatar, String password,
			Set<Address> addresses, Set<Order> orders, Set<Comment> comments, Set<Feedback> feedbacks, Set<Cart> carts) {
		this.role = role;
		this.lastName = lastName;
		this.firstName = firstName;
		this.email = email;
		this.phoneNumber = phoneNumber;
		this.avatar = avatar;
		this.state = 1;
		this.password = password;
		this.addresses = addresses;
		this.orders = orders;
		this.comments = comments;
		this.feedbacks = feedbacks;
		this.carts = carts;
	}

	public int getAccountId() {
		return this.accountId;
	}

	public void setAccountId(int accountId) {
		this.accountId = accountId;
	}

	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	public String getAvatar() {
		return this.avatar;
	}

	public void setAvatar(String avatar) {
		this.avatar = avatar;
	}

	public int getState() {
		return this.state;
	}

	public void setState(int state) {
		this.state = state;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Set<Address> getAddresses() {
		return this.addresses;
	}

	public void setAddresses(Set<Address> addresses) {
		this.addresses = addresses;
	}

	public Set<Order> getOrders() {
		return this.orders;
	}

	public void setOrders(Set<Order> orders) {
		this.orders = orders;
	}

	public Set<Comment> getComments() {
		return this.comments;
	}

	public void setComments(Set<Comment> comments) {
		this.comments = comments;
	}

	public Set<Feedback> getFeedbacks() {
		return this.feedbacks;
	}

	public void setFeedbacks(Set<Feedback> feedbacks) {
		this.feedbacks = feedbacks;
	}

	public Set<Cart> getCarts() {
		return this.carts;
	}

	public void setCarts(Set<Cart> carts) {
		this.carts = carts;
	}
	
	public String toString()
	{
		return String.format("Account ID: {0}", accountId);
	}
}
