package tad.entity;
// Generated Apr 8, 2023, 3:38:47 PM by Hibernate Tools 3.6.2.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Address generated by hbm2java
 */
@Entity
@Table(name = "Address", schema = "dbo", catalog = "DB_Tad")
public class Address {

	private int addressId;
	private Ward ward;
	private String name;
	private Set<Account> accounts = new HashSet<Account>(0);

	public Address() {
	}

	public Address(int addressId, Ward ward) {
		this.addressId = addressId;
		this.ward = ward;
	}

	public Address(int addressId, Ward ward, String name, Set<Account> accounts) {
		this.addressId = addressId;
		this.ward = ward;
		this.name = name;
		this.accounts = accounts;
	}

	@Id

	@Column(name = "AddressID", unique = true, nullable = false)
	public int getAddressId() {
		return this.addressId;
	}

	public void setAddressId(int addressId) {
		this.addressId = addressId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "WardID", nullable = false)
	public Ward getWard() {
		return this.ward;
	}

	public void setWard(Ward ward) {
		this.ward = ward;
	}

	@Column(name = "Name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "AddressAccount", schema = "dbo", catalog = "DB_Tad", joinColumns = {
			@JoinColumn(name = "AddressID", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "AccountID", nullable = false, updatable = false) })
	public Set<Account> getAccounts() {
		return this.accounts;
	}

	public void setAccounts(Set<Account> accounts) {
		this.accounts = accounts;
	}

}
