package tad.entity;
// Generated Apr 3, 2023, 10:50:00 AM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Admin generated by hbm2java
 */
@Entity
@Table(name = "Admin", schema = "dbo", catalog = "DB_Tad")
public class Admin {

	@Id
	@Column(name = "AdminID", unique = true, nullable = false)
	private String adminId;

	@Column(name = "Email", nullable = false)
	private String email;

	@Column(name = "Password", nullable = false)
	private String password;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "admin")
	private Set<Category> categories = new HashSet<>(0);

	public Admin() {
	}

	public Admin(String adminId, String email, String password) {
		this.adminId = adminId;
		this.email = email;
		this.password = password;
	}

	public Admin(String adminId, String email, String password, Set<Category> categories) {
		this.adminId = adminId;
		this.email = email;
		this.password = password;
		this.categories = categories;
	}

	public String getAdminId() {
		return this.adminId;
	}

	public void setAdminId(String adminId) {
		this.adminId = adminId;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Set<Category> getCategories() {
		return this.categories;
	}

	public void setCategories(Set<Category> categories) {
		this.categories = categories;
	}
}
