package tad.entity;
// Generated Apr 8, 2023, 3:38:47 PM by Hibernate Tools 3.6.2.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name = "Category", schema = "dbo", catalog = "DB_Tad")
public class Category {

	private int categoryId;
	private String name;
	
	@Column(name = "Image")
	private String image;
	private Set<Product> products = new HashSet<Product>(0);

	public Category() {
	}

	public Category(int categoryId, String name, String image) {
		this.categoryId = categoryId;
		this.name = name;
		this.image = image;
	}

	public Category(int categoryId, Account account, String name, Set<Product> products) {
		this.categoryId = categoryId;
		this.name = name;
		this.products = products;
	}

	@Id

	@Column(name = "CategoryID", unique = true, nullable = false)
	public int getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(int categoryId) {
		this.categoryId = categoryId;
	}

	@Column(name = "Name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "category")
	public Set<Product> getProducts() {
		return this.products;
	}

	public void setProducts(Set<Product> products) {
		this.products = products;
	}

	public String getImage() {
		return image;
	}

	public void setImage(String image) {
		this.image = image;
	}

}
