package tad.entity;
// Generated Apr 3, 2023, 10:50:00 AM by Hibernate Tools 4.3.6.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name = "Category", schema = "dbo", catalog = "DB_Tad")
public class Category implements java.io.Serializable {

	private Serializable categoryId;
	private Admin admin;
	private Serializable name;
	private Set<Product> products = new HashSet<Product>(0);

	public Category() {
	}

	public Category(Serializable categoryId, Admin admin, Serializable name) {
		this.categoryId = categoryId;
		this.admin = admin;
		this.name = name;
	}

	public Category(Serializable categoryId, Admin admin, Serializable name, Set<Product> products) {
		this.categoryId = categoryId;
		this.admin = admin;
		this.name = name;
		this.products = products;
	}

	@Id

	@Column(name = "CategoryID", unique = true, nullable = false)
	public Serializable getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Serializable categoryId) {
		this.categoryId = categoryId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "AdminID", nullable = false)
	public Admin getAdmin() {
		return this.admin;
	}

	public void setAdmin(Admin admin) {
		this.admin = admin;
	}

	@Column(name = "Name", nullable = false)
	public Serializable getName() {
		return this.name;
	}

	public void setName(Serializable name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "category")
	public Set<Product> getProducts() {
		return this.products;
	}

	public void setProducts(Set<Product> products) {
		this.products = products;
	}

}
