package tad.entity;
// Generated Apr 3, 2023, 10:50:00 AM by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Coupon generated by hbm2java
 */
@Entity
@Table(name = "Coupon", schema = "dbo", catalog = "DB_Tad")
public class Coupon {
	@Id
	@Column(name = "CouponID", unique = true, nullable = false)
	private String couponId;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ShopID")
	private ShopSystem shopSystem;
	
	@Column(name = "TypeCoupon", nullable = false)
	private boolean typeCoupon;
	
	@Column(name = "Name", nullable = false)
	private String name;

	@Column(name = "Discount", nullable = false, precision = 53, scale = 0)
	private double discount;
	

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PostingDate", nullable = false, length = 23)
	private Date postingDate;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ExpiryDate", nullable = false, length = 23)
	private Date expiryDate;
	
	@Column(name = "Quantity", nullable = false)
	private int quantity;
	
	@Column(name = "Detail")
	private String detail;
	
	@Column(name = "Status", nullable = false)
	private boolean status;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "coupon")
	private Set<OrderDetail> orderDetails = new HashSet<OrderDetail>(0);
	
	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "coupons")
	private Set<Product> products = new HashSet<Product>(0);

	public Coupon() {
	}

	public Coupon(String couponId, boolean typeCoupon, String name, double discount, Date postingDate, Date expiryDate,
			int quantity, boolean status) {
		this.couponId = couponId;
		this.typeCoupon = typeCoupon;
		this.name = name;
		this.discount = discount;
		this.postingDate = postingDate;
		this.expiryDate = expiryDate;
		this.quantity = quantity;
		this.status = status;
	}

	public Coupon(String couponId, ShopSystem shopSystem, boolean typeCoupon, String name, double discount,
			Date postingDate, Date expiryDate, int quantity, String detail, boolean status,
			Set<OrderDetail> orderDetails, Set<Product> products) {
		this.couponId = couponId;
		this.shopSystem = shopSystem;
		this.typeCoupon = typeCoupon;
		this.name = name;
		this.discount = discount;
		this.postingDate = postingDate;
		this.expiryDate = expiryDate;
		this.quantity = quantity;
		this.detail = detail;
		this.status = status;
		this.orderDetails = orderDetails;
		this.products = products;
	}

	public String getCouponId() {
		return this.couponId;
	}

	public void setCouponId(String couponId) {
		this.couponId = couponId;
	}

	public ShopSystem getShopSystem() {
		return this.shopSystem;
	}

	public void setShopSystem(ShopSystem shopSystem) {
		this.shopSystem = shopSystem;
	}

	
	public boolean isTypeCoupon() {
		return this.typeCoupon;
	}

	public void setTypeCoupon(boolean typeCoupon) {
		this.typeCoupon = typeCoupon;
	}

	
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public double getDiscount() {
		return this.discount;
	}

	public void setDiscount(double discount) {
		this.discount = discount;
	}

	public Date getPostingDate() {
		return this.postingDate;
	}

	public void setPostingDate(Date postingDate) {
		this.postingDate = postingDate;
	}

	public Date getExpiryDate() {
		return this.expiryDate;
	}

	public void setExpiryDate(Date expiryDate) {
		this.expiryDate = expiryDate;
	}

	
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	
	public String getDetail() {
		return this.detail;
	}

	public void setDetail(String detail) {
		this.detail = detail;
	}

	
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	
	public Set<OrderDetail> getOrderDetails() {
		return this.orderDetails;
	}

	public void setOrderDetails(Set<OrderDetail> orderDetails) {
		this.orderDetails = orderDetails;
	}

	
	public Set<Product> getProducts() {
		return this.products;
	}

	public void setProducts(Set<Product> products) {
		this.products = products;
	}

}
