package tad.entity;
// Generated Apr 3, 2023, 10:50:00 AM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * District generated by hbm2java
 */
@Entity
@Table(name = "District", schema = "dbo", catalog = "DB_Tad")
public class District{
	@Id
	@Column(name = "DistrictID", unique = true, nullable = false)
	private String districtId;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ProvinceID", nullable = false)
	private Province province;
	
	@Column(name = "Name", nullable = false)
	private String name;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "district")
	private Set<Ward> wards = new HashSet<Ward>(0);

	public District() {
	}

	public District(String districtId, Province province, String name) {
		this.districtId = districtId;
		this.province = province;
		this.name = name;
	}

	public District(String districtId, Province province, String name, Set<Ward> wards) {
		this.districtId = districtId;
		this.province = province;
		this.name = name;
		this.wards = wards;
	}

	
	public String getDistrictId() {
		return this.districtId;
	}

	public void setDistrictId(String districtId) {
		this.districtId = districtId;
	}

	
	public Province getProvince() {
		return this.province;
	}

	public void setProvince(Province province) {
		this.province = province;
	}

	
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	
	public Set<Ward> getWards() {
		return this.wards;
	}

	public void setWards(Set<Ward> wards) {
		this.wards = wards;
	}

}
