package tad.entity;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Feedback generated by hbm2java
 */
@Entity
@Table(name = "Feedback", schema = "dbo", catalog = "DB_Tad", uniqueConstraints = @UniqueConstraint(columnNames = {
		"AccountID", "ProductID" }))
public class Feedback {
	@Id
	@Column(name = "FeedbackID", unique = true, nullable = false)
	private int feedbackId;

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "AccountID", nullable = false)
	private Account account;

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ProductID", nullable = false)
	private Product product;

	@Column(name = "RatingStar", nullable = false)
	private short ratingStar;

	@Column(name = "FeedbackContent")
	private String feedbackContent;

	@Column(name = "Status", nullable = false)
	private short status;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PostingDate", nullable = false, length = 23)
	private Date postingDate;

	@OneToOne(mappedBy = "feedback")
	private Comment comment;

	public Feedback() {
	}

	public Feedback(int feedbackId, Account account, Product product, short ratingStar, short status,
			Date postingDate) {
		this.feedbackId = feedbackId;
		this.account = account;
		this.product = product;
		this.ratingStar = ratingStar;
		this.status = status;
		this.postingDate = postingDate;
	}

	public int getFeedbackId() {
		return this.feedbackId;
	}

	public void setFeedbackId(int feedbackId) {
		this.feedbackId = feedbackId;
	}

	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	public short getRatingStar() {
		return this.ratingStar;
	}

	public void setRatingStar(short ratingStar) {
		this.ratingStar = ratingStar;
	}

	public String getFeedbackContent() {
		return this.feedbackContent;
	}

	public void setFeedbackContent(String feedbackContent) {
		this.feedbackContent = feedbackContent;
	}

	public Date getPostingDate() {
		return this.postingDate;
	}

	public void setPostingDate(Date postingDate) {
		this.postingDate = postingDate;
	}

	public short getStatus() {
		return status;
	}

	public Comment getComment() {
		return comment;
	}

	public void setComment(Comment comment) {
		this.comment = comment;
	}

	public void setStatus(short status) {
		this.status = status;
	}

}
