package tad.entity;
// Generated Apr 3, 2023, 10:50:00 AM by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Feedback generated by hbm2java
 */
@Entity
@Table(name = "Feedback", schema = "dbo", catalog = "DB_Tad", uniqueConstraints = @UniqueConstraint(columnNames = {
		"UserID", "ProductID" }))
public class Feedback {

	@Id
	@Column(name = "FeedbackID", unique = true, nullable = false)
	private String feedbackId;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ProductID", nullable = false)
	private Product product;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UserID", nullable = false)
	private User user;


	@Column(name = "RatingStar", nullable = false)
	private short ratingStar;


	@Column(name = "FeedbackContent")
	private String feedbackContent;


	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PostingDate", nullable = false, length = 23)
	private Date postingDate;

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "FeedbackHistory", schema = "dbo", catalog = "DB_Tad", joinColumns = {
			@JoinColumn(name = "FeedbackID", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "CommentID", nullable = false, updatable = false) })
	private Set<Comment> comments = new HashSet<>(0);

	public Feedback() {
	}

	public Feedback(String feedbackId, Product product, User user, short ratingStar, Date postingDate) {
		this.feedbackId = feedbackId;
		this.product = product;
		this.user = user;
		this.ratingStar = ratingStar;
		this.postingDate = postingDate;
	}

	public Feedback(String feedbackId, Product product, User user, short ratingStar, String feedbackContent,
			Date postingDate, Set<Comment> comments) {
		this.feedbackId = feedbackId;
		this.product = product;
		this.user = user;
		this.ratingStar = ratingStar;
		this.feedbackContent = feedbackContent;
		this.postingDate = postingDate;
		this.comments = comments;
	}

	public String getFeedbackId() {
		return this.feedbackId;
	}

	public void setFeedbackId(String feedbackId) {
		this.feedbackId = feedbackId;
	}


	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}


	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public short getRatingStar() {
		return this.ratingStar;
	}

	public void setRatingStar(short ratingStar) {
		this.ratingStar = ratingStar;
	}

	public String getFeedbackContent() {
		return this.feedbackContent;
	}

	public void setFeedbackContent(String feedbackContent) {
		this.feedbackContent = feedbackContent;
	}

	public Date getPostingDate() {
		return this.postingDate;
	}

	public void setPostingDate(Date postingDate) {
		this.postingDate = postingDate;
	}


	public Set<Comment> getComments() {
		return this.comments;
	}

	public void setComments(Set<Comment> comments) {
		this.comments = comments;
	}

}
