package tad.entity;
// Generated Apr 8, 2023, 3:38:47 PM by Hibernate Tools 3.6.2.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Feedback generated by hbm2java
 */
@Entity
@Table(name = "Feedback", schema = "dbo", catalog = "DB_Tad", uniqueConstraints = @UniqueConstraint(columnNames = {
		"AccountID", "ProductID" }))
public class Feedback  {

	private int feedbackId;
	private Account account;
	private Product product;
	private short ratingStar;
	private String feedbackContent;
	private Date postingDate;
	private Set<Comment> comments = new HashSet<Comment>(0);

	public Feedback() {
	}

	public Feedback(int feedbackId, Account account, Product product, short ratingStar, Date postingDate) {
		this.feedbackId = feedbackId;
		this.account = account;
		this.product = product;
		this.ratingStar = ratingStar;
		this.postingDate = postingDate;
	}

	public Feedback(int feedbackId, Account account, Product product, short ratingStar, String feedbackContent,
			Date postingDate, Set<Comment> comments) {
		this.feedbackId = feedbackId;
		this.account = account;
		this.product = product;
		this.ratingStar = ratingStar;
		this.feedbackContent = feedbackContent;
		this.postingDate = postingDate;
		this.comments = comments;
	}

	@Id

	@Column(name = "FeedbackID", unique = true, nullable = false)
	public int getFeedbackId() {
		return this.feedbackId;
	}

	public void setFeedbackId(int feedbackId) {
		this.feedbackId = feedbackId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "AccountID", nullable = false)
	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ProductID", nullable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@Column(name = "RatingStar", nullable = false)
	public short getRatingStar() {
		return this.ratingStar;
	}

	public void setRatingStar(short ratingStar) {
		this.ratingStar = ratingStar;
	}

	@Column(name = "FeedbackContent")
	public String getFeedbackContent() {
		return this.feedbackContent;
	}

	public void setFeedbackContent(String feedbackContent) {
		this.feedbackContent = feedbackContent;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PostingDate", nullable = false, length = 23)
	public Date getPostingDate() {
		return this.postingDate;
	}

	public void setPostingDate(Date postingDate) {
		this.postingDate = postingDate;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "FeedbackHistory", schema = "dbo", catalog = "DB_Tad", joinColumns = {
			@JoinColumn(name = "FeedbackID", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "CommentID", nullable = false, updatable = false) })
	public Set<Comment> getComments() {
		return this.comments;
	}

	public void setComments(Set<Comment> comments) {
		this.comments = comments;
	}

}
