package tad.entity;
// Generated Apr 3, 2023, 10:50:00 AM by Hibernate Tools 4.3.6.Final
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Order generated by hbm2java
 */
@Entity
@Table(name = "Order", schema = "dbo", catalog = "DB_Tad")
public class Order {
	@Id
	@Column(name = "OrderID", unique = true, nullable = false)
	private String orderId;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UserID", nullable = false)
	private User user;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "OrderTime", nullable = false, length = 23)
	private Date orderTime;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DeliveryTime", length = 23)
	private Date deliveryTime;

	@Column(name = "Status", nullable = false)
	private short status;


	@OneToMany(fetch = FetchType.LAZY, mappedBy = "order")
	private Set<OrderDetail> orderDetails = new HashSet<>(0);

	public Order() {
	}

	public Order(String orderId, User user, Date orderTime, short status) {
		this.orderId = orderId;
		this.user = user;
		this.orderTime = orderTime;
		this.status = status;
	}

	public Order(String orderId, User user, Date orderTime, Date deliveryTime, short status,
			Set<OrderDetail> orderDetails) {
		this.orderId = orderId;
		this.user = user;
		this.orderTime = orderTime;
		this.deliveryTime = deliveryTime;
		this.status = status;
		this.orderDetails = orderDetails;
	}


	public String getOrderId() {
		return this.orderId;
	}

	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Date getOrderTime() {
		return this.orderTime;
	}

	public void setOrderTime(Date orderTime) {
		this.orderTime = orderTime;
	}

	public Date getDeliveryTime() {
		return this.deliveryTime;
	}

	public void setDeliveryTime(Date deliveryTime) {
		this.deliveryTime = deliveryTime;
	}


	public short getStatus() {
		return this.status;
	}

	public void setStatus(short status) {
		this.status = status;
	}

	public Set<OrderDetail> getOrderDetails() {
		return this.orderDetails;
	}

	public void setOrderDetails(Set<OrderDetail> orderDetails) {
		this.orderDetails = orderDetails;
	}

}
