package tad.entity;
// Generated Apr 3, 2023, 10:50:00 AM by Hibernate Tools 4.3.6.Final

import java.io.Serializable;
import java.util.Arrays;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OrderDetailId generated by hbm2java
 */
@Embeddable
public class OrderDetailId implements Serializable{

	@Column(name = "ProductID", nullable = false)
	private String productId;


	@Column(name = "OrderID", nullable = false)
	private byte[] orderId;

	@Column(name = "CouponID", nullable = false)
	private byte[] couponId;

	public OrderDetailId() {
	}

	public OrderDetailId(String productId, byte[] orderId, byte[] couponId) {
		this.productId = productId;
		this.orderId = orderId;
		this.couponId = couponId;
	}

	public String getProductId() {
		return this.productId;
	}

	public void setProductId(String productId) {
		this.productId = productId;
	}

	public byte[] getOrderId() {
		return this.orderId;
	}

	public void setOrderId(byte[] orderId) {
		this.orderId = orderId;
	}

	public byte[] getCouponId() {
		return this.couponId;
	}

	public void setCouponId(byte[] couponId) {
		this.couponId = couponId;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null) || !(other instanceof OrderDetailId))
			return false;
		OrderDetailId castOther = (OrderDetailId) other;

		return ((this.getProductId() == castOther.getProductId()) || (this.getProductId() != null
				&& castOther.getProductId() != null && this.getProductId().equals(castOther.getProductId())))
				&& ((this.getOrderId() == castOther.getOrderId()) || (this.getOrderId() != null
						&& castOther.getOrderId() != null && Arrays.equals(this.getOrderId(), castOther.getOrderId())))
				&& ((this.getCouponId() == castOther.getCouponId())
						|| (this.getCouponId() != null && castOther.getCouponId() != null
								&& Arrays.equals(this.getCouponId(), castOther.getCouponId())));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (getProductId() == null ? 0 : this.getProductId().hashCode());
		result = 37 * result + (getOrderId() == null ? 0 : Arrays.hashCode(this.getOrderId()));
		result = 37 * result + (getCouponId() == null ? 0 : Arrays.hashCode(this.getCouponId()));
		return result;
	}

}
