package tad.entity;
// Generated Apr 8, 2023, 3:38:47 PM by Hibernate Tools 3.6.2.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OrderDetail generated by hbm2java
 */
@Entity
@Table(name = "OrderDetail", schema = "dbo", catalog = "DB_Tad")
public class OrderDetail {

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "productId", column = @Column(name = "ProductID", nullable = false)),
			@AttributeOverride(name = "orderId", column = @Column(name = "OrderID", nullable = false)),
			@AttributeOverride(name = "couponId", column = @Column(name = "CouponID", nullable = false)) })
	private OrderDetailId id;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "OrderID", nullable = false, insertable = false, updatable = false)
	private Order order;
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CouponID", nullable = false, insertable = false, updatable = false)
	private Coupon coupon;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ProductID", nullable = false, insertable = false, updatable = false)
	private Product product;

	public OrderDetail() {
	}

	public OrderDetail(OrderDetailId id, Order order, Coupon coupon, Product product) {
		this.id = id;
		this.order = order;
		this.coupon = coupon;
		this.product = product;
	}

	public OrderDetailId getId() {
		return this.id;
	}

	public void setId(OrderDetailId id) {
		this.id = id;
	}

	public Order getOrder() {
		return this.order;
	}

	public void setOrder(Order order) {
		this.order = order;
	}

	public Coupon getCoupon() {
		return this.coupon;
	}

	public void setCoupon(Coupon coupon) {
		this.coupon = coupon;
	}

	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

}
