package tad.entity;
// Generated Apr 3, 2023, 10:50:00 AM by Hibernate Tools 4.3.6.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Province generated by hbm2java
 */
@Entity
@Table(name = "Province", schema = "dbo", catalog = "DB_Tad")
public class Province implements java.io.Serializable {

	private Serializable provinceId;
	private Serializable name;
	private Set<District> districts = new HashSet<District>(0);

	public Province() {
	}

	public Province(Serializable provinceId, Serializable name) {
		this.provinceId = provinceId;
		this.name = name;
	}

	public Province(Serializable provinceId, Serializable name, Set<District> districts) {
		this.provinceId = provinceId;
		this.name = name;
		this.districts = districts;
	}

	@Id

	@Column(name = "ProvinceID", unique = true, nullable = false)
	public Serializable getProvinceId() {
		return this.provinceId;
	}

	public void setProvinceId(Serializable provinceId) {
		this.provinceId = provinceId;
	}

	@Column(name = "Name", nullable = false)
	public Serializable getName() {
		return this.name;
	}

	public void setName(Serializable name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "province")
	public Set<District> getDistricts() {
		return this.districts;
	}

	public void setDistricts(Set<District> districts) {
		this.districts = districts;
	}

}
