package tad.entity;
// Generated Apr 3, 2023, 10:50:00 AM by Hibernate Tools 4.3.6.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ShopSystem generated by hbm2java
 */
@Entity
@Table(name = "ShopSystem", schema = "dbo", catalog = "DB_Tad")
public class ShopSystem implements java.io.Serializable {

	private Serializable shopId;
	private User user;
	private Serializable name;
	private byte[] logoShop;
	private Serializable email;
	private Set<User> users = new HashSet<User>(0);
	private Set<Product> products = new HashSet<Product>(0);
	private Set<Coupon> coupons = new HashSet<Coupon>(0);
	private Set<Address> addresses = new HashSet<Address>(0);

	public ShopSystem() {
	}

	public ShopSystem(Serializable shopId, User user, Serializable name) {
		this.shopId = shopId;
		this.user = user;
		this.name = name;
	}

	public ShopSystem(Serializable shopId, User user, Serializable name, byte[] logoShop, Serializable email,
			Set<User> users, Set<Product> products, Set<Coupon> coupons, Set<Address> addresses) {
		this.shopId = shopId;
		this.user = user;
		this.name = name;
		this.logoShop = logoShop;
		this.email = email;
		this.users = users;
		this.products = products;
		this.coupons = coupons;
		this.addresses = addresses;
	}

	@Id

	@Column(name = "ShopID", unique = true, nullable = false)
	public Serializable getShopId() {
		return this.shopId;
	}

	public void setShopId(Serializable shopId) {
		this.shopId = shopId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UserID", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "Name", nullable = false)
	public Serializable getName() {
		return this.name;
	}

	public void setName(Serializable name) {
		this.name = name;
	}

	@Column(name = "LogoShop")
	public byte[] getLogoShop() {
		return this.logoShop;
	}

	public void setLogoShop(byte[] logoShop) {
		this.logoShop = logoShop;
	}

	@Column(name = "Email")
	public Serializable getEmail() {
		return this.email;
	}

	public void setEmail(Serializable email) {
		this.email = email;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "shopSystem")
	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "shopSystem")
	public Set<Product> getProducts() {
		return this.products;
	}

	public void setProducts(Set<Product> products) {
		this.products = products;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "shopSystem")
	public Set<Coupon> getCoupons() {
		return this.coupons;
	}

	public void setCoupons(Set<Coupon> coupons) {
		this.coupons = coupons;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "shopSystems")
	public Set<Address> getAddresses() {
		return this.addresses;
	}

	public void setAddresses(Set<Address> addresses) {
		this.addresses = addresses;
	}

}
