package tad.entity;
// Generated Apr 8, 2023, 3:38:47 PM by Hibernate Tools 3.6.2.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ShopSystem generated by hbm2java
 */
@Entity
@Table(name = "ShopSystem", schema = "dbo", catalog = "DB_Tad")
public class ShopSystem{

	private int shopId;
	private Account account;
	private String name;
	private byte[] logoShop;
	private String email;
	private String addressId;
	private Set<Account> accounts = new HashSet<Account>(0);
	private Set<Product> products = new HashSet<Product>(0);
	private Set<Coupon> coupons = new HashSet<Coupon>(0);

	public ShopSystem() {
	}

	public ShopSystem(int shopId, Account account, String name, String addressId) {
		this.shopId = shopId;
		this.account = account;
		this.name = name;
		this.addressId = addressId;
	}

	public ShopSystem(int shopId, Account account, String name, byte[] logoShop, String email,
			String addressId, Set<Account> accounts, Set<Product> products, Set<Coupon> coupons) {
		this.shopId = shopId;
		this.account = account;
		this.name = name;
		this.logoShop = logoShop;
		this.email = email;
		this.addressId = addressId;
		this.accounts = accounts;
		this.products = products;
		this.coupons = coupons;
	}

	@Id

	@Column(name = "ShopID", unique = true, nullable = false)
	public int getShopId() {
		return this.shopId;
	}

	public void setShopId(int shopId) {
		this.shopId = shopId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "AccountID", nullable = false)
	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	@Column(name = "Name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "LogoShop")
	public byte[] getLogoShop() {
		return this.logoShop;
	}

	public void setLogoShop(byte[] logoShop) {
		this.logoShop = logoShop;
	}

	@Column(name = "Email")
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "AddressID", nullable = false)
	public String getAddressId() {
		return this.addressId;
	}

	public void setAddressId(String addressId) {
		this.addressId = addressId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "shopSystem")
	public Set<Account> getAccounts() {
		return this.accounts;
	}

	public void setAccounts(Set<Account> accounts) {
		this.accounts = accounts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "shopSystem")
	public Set<Product> getProducts() {
		return this.products;
	}

	public void setProducts(Set<Product> products) {
		this.products = products;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "shopSystem")
	public Set<Coupon> getCoupons() {
		return this.coupons;
	}

	public void setCoupons(Set<Coupon> coupons) {
		this.coupons = coupons;
	}

}
