package tad.entity;
// Generated Apr 3, 2023, 10:50:00 AM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ShopSystem generated by hbm2java
 */
@Entity
@Table(name = "ShopSystem", schema = "dbo", catalog = "DB_Tad")
public class ShopSystem {

	@Id
	@Column(name = "ShopID", unique = true, nullable = false)
	private String shopId;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UserID", nullable = false)
	private User user;

	@Column(name = "Name", nullable = false)
	private String name;

	@Column(name = "LogoShop")
	private byte[] logoShop;

	@Column(name = "Email")
	private String email;


	@OneToMany(fetch = FetchType.LAZY, mappedBy = "shopSystem")
	private Set<User> users = new HashSet<>(0);

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "shopSystem")
	private Set<Product> products = new HashSet<>(0);

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "shopSystem")
	private Set<Coupon> coupons = new HashSet<>(0);


	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "shopSystems")
	private Set<Address> addresses = new HashSet<>(0);

	public ShopSystem() {
	}

	public ShopSystem(String shopId, User user, String name) {
		this.shopId = shopId;
		this.user = user;
		this.name = name;
	}

	public ShopSystem(String shopId, User user, String name, byte[] logoShop, String email,
			Set<User> users, Set<Product> products, Set<Coupon> coupons, Set<Address> addresses) {
		this.shopId = shopId;
		this.user = user;
		this.name = name;
		this.logoShop = logoShop;
		this.email = email;
		this.users = users;
		this.products = products;
		this.coupons = coupons;
		this.addresses = addresses;
	}

	public String getShopId() {
		return this.shopId;
	}

	public void setShopId(String shopId) {
		this.shopId = shopId;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public byte[] getLogoShop() {
		return this.logoShop;
	}

	public void setLogoShop(byte[] logoShop) {
		this.logoShop = logoShop;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

	public Set<Product> getProducts() {
		return this.products;
	}

	public void setProducts(Set<Product> products) {
		this.products = products;
	}

	public Set<Coupon> getCoupons() {
		return this.coupons;
	}

	public void setCoupons(Set<Coupon> coupons) {
		this.coupons = coupons;
	}

	public Set<Address> getAddresses() {
		return this.addresses;
	}

	public void setAddresses(Set<Address> addresses) {
		this.addresses = addresses;
	}

}
