package tad.entity;
// Generated Apr 3, 2023, 10:50:00 AM by Hibernate Tools 4.3.6.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "User", schema = "dbo", catalog = "DB_Tad")
public class User implements java.io.Serializable {

	private Serializable userId;
	private ShopSystem shopSystem;
	private Serializable lastName;
	private Serializable firstName;
	private Serializable email;
	private Serializable phoneNumber;
	private byte[] avatar;
	private int state;
	private Serializable password;
	private Set<Order> orders = new HashSet<Order>(0);
	private Set<ShopSystem> shopSystems = new HashSet<ShopSystem>(0);
	private Set<Comment> comments = new HashSet<Comment>(0);
	private Set<Cart> carts = new HashSet<Cart>(0);
	private Set<Address> addresses = new HashSet<Address>(0);
	private Set<Feedback> feedbacks = new HashSet<Feedback>(0);

	public User() {
	}

	public User(Serializable userId, Serializable lastName, Serializable firstName, Serializable email, int state,
			Serializable password) {
		this.userId = userId;
		this.lastName = lastName;
		this.firstName = firstName;
		this.email = email;
		this.state = state;
		this.password = password;
	}

	public User(Serializable userId, ShopSystem shopSystem, Serializable lastName, Serializable firstName,
			Serializable email, Serializable phoneNumber, byte[] avatar, int state, Serializable password,
			Set<Order> orders, Set<ShopSystem> shopSystems, Set<Comment> comments, Set<Cart> carts,
			Set<Address> addresses, Set<Feedback> feedbacks) {
		this.userId = userId;
		this.shopSystem = shopSystem;
		this.lastName = lastName;
		this.firstName = firstName;
		this.email = email;
		this.phoneNumber = phoneNumber;
		this.avatar = avatar;
		this.state = state;
		this.password = password;
		this.orders = orders;
		this.shopSystems = shopSystems;
		this.comments = comments;
		this.carts = carts;
		this.addresses = addresses;
		this.feedbacks = feedbacks;
	}

	@Id

	@Column(name = "UserID", unique = true, nullable = false)
	public Serializable getUserId() {
		return this.userId;
	}

	public void setUserId(Serializable userId) {
		this.userId = userId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ShopID")
	public ShopSystem getShopSystem() {
		return this.shopSystem;
	}

	public void setShopSystem(ShopSystem shopSystem) {
		this.shopSystem = shopSystem;
	}

	@Column(name = "LastName", nullable = false)
	public Serializable getLastName() {
		return this.lastName;
	}

	public void setLastName(Serializable lastName) {
		this.lastName = lastName;
	}

	@Column(name = "FirstName", nullable = false)
	public Serializable getFirstName() {
		return this.firstName;
	}

	public void setFirstName(Serializable firstName) {
		this.firstName = firstName;
	}

	@Column(name = "Email", nullable = false)
	public Serializable getEmail() {
		return this.email;
	}

	public void setEmail(Serializable email) {
		this.email = email;
	}

	@Column(name = "PhoneNumber")
	public Serializable getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(Serializable phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	@Column(name = "Avatar")
	public byte[] getAvatar() {
		return this.avatar;
	}

	public void setAvatar(byte[] avatar) {
		this.avatar = avatar;
	}

	@Column(name = "State", nullable = false)
	public int getState() {
		return this.state;
	}

	public void setState(int state) {
		this.state = state;
	}

	@Column(name = "Password", nullable = false)
	public Serializable getPassword() {
		return this.password;
	}

	public void setPassword(Serializable password) {
		this.password = password;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Order> getOrders() {
		return this.orders;
	}

	public void setOrders(Set<Order> orders) {
		this.orders = orders;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<ShopSystem> getShopSystems() {
		return this.shopSystems;
	}

	public void setShopSystems(Set<ShopSystem> shopSystems) {
		this.shopSystems = shopSystems;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Comment> getComments() {
		return this.comments;
	}

	public void setComments(Set<Comment> comments) {
		this.comments = comments;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Cart> getCarts() {
		return this.carts;
	}

	public void setCarts(Set<Cart> carts) {
		this.carts = carts;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<Address> getAddresses() {
		return this.addresses;
	}

	public void setAddresses(Set<Address> addresses) {
		this.addresses = addresses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Feedback> getFeedbacks() {
		return this.feedbacks;
	}

	public void setFeedbacks(Set<Feedback> feedbacks) {
		this.feedbacks = feedbacks;
	}

}
